/**
 * CSS EXPORT
 * 
 * Export token configurations as CSS custom properties.
 */

import type { CustomToken, TokenCategory } from "../types";
import type { ResolvedComponentTokens } from "../resolver";

// ============================================
// TYPES
// ============================================

export interface CSSExportOptions {
  prefix?: string;
  includeComments?: boolean;
  selector?: string;
  darkModeSelector?: string;
  format?: "minified" | "formatted";
}

export interface CSSExportResult {
  css: string;
  lightMode: string;
  darkMode?: string;
  tokenCount: number;
}

// ============================================
// CUSTOM TOKENS EXPORT
// ============================================

/**
 * Export custom tokens as CSS custom properties
 */
export function exportCustomTokensAsCSS(
  tokens: CustomToken[],
  options: CSSExportOptions = {}
): string {
  const {
    prefix = "custom",
    includeComments = true,
    selector = ":root",
    format = "formatted",
  } = options;

  const lines: string[] = [];
  const indent = format === "formatted" ? "  " : "";
  const newline = format === "formatted" ? "\n" : "";

  lines.push(`${selector} {${newline}`);

  // Group by category
  const grouped = groupTokensByCategory(tokens);

  for (const [category, categoryTokens] of Object.entries(grouped)) {
    if (includeComments) {
      lines.push(`${newline}${indent}/* ${category.toUpperCase()} */${newline}`);
    }

    for (const token of categoryTokens) {
      const varName = `--${prefix}-${token.id}`;
      const value = formatTokenValue(token);

      if (includeComments && token.description) {
        lines.push(`${indent}/* ${token.description} */${newline}`);
      }

      lines.push(`${indent}${varName}: ${value};${newline}`);
    }
  }

  lines.push(`}${newline}`);

  return lines.join("");
}

// ============================================
// COMPONENT TOKENS EXPORT
// ============================================

/**
 * Export resolved component tokens as CSS
 */
export function exportComponentTokensAsCSS(
  componentName: string,
  resolved: ResolvedComponentTokens,
  options: CSSExportOptions = {}
): string {
  const {
    prefix = componentName.toLowerCase(),
    includeComments = true,
    selector = ":root",
    format = "formatted",
  } = options;

  const lines: string[] = [];
  const indent = format === "formatted" ? "  " : "";
  const newline = format === "formatted" ? "\n" : "";

  if (includeComments) {
    lines.push(`/* ${componentName} Component Tokens */${newline}`);
  }

  lines.push(`${selector} {${newline}`);

  for (const [key, value] of Object.entries(resolved)) {
    // Convert key like "background@root@default" to CSS variable
    const varName = `--${prefix}-${key.replace(/@/g, "-")}`;
    lines.push(`${indent}${varName}: ${value};${newline}`);
  }

  lines.push(`}${newline}`);

  return lines.join("");
}

// ============================================
// FULL EXPORT
// ============================================

/**
 * Export all tokens and overrides as a complete CSS file
 */
export function exportFullCSS(
  customTokens: CustomToken[],
  componentOverrides: Record<string, ResolvedComponentTokens>,
  options: CSSExportOptions = {}
): CSSExportResult {
  const {
    includeComments = true,
    selector = ":root",
    darkModeSelector = ".dark",
    format = "formatted",
  } = options;

  const newline = format === "formatted" ? "\n" : "";
  const lines: string[] = [];
  let tokenCount = 0;

  // Header comment
  if (includeComments) {
    lines.push(`/**${newline}`);
    lines.push(` * Design Tokens${newline}`);
    lines.push(` * Generated by Component Token Editor${newline}`);
    lines.push(` * ${new Date().toISOString()}${newline}`);
    lines.push(` */${newline}${newline}`);
  }

  // Custom tokens
  if (customTokens.length > 0) {
    if (includeComments) {
      lines.push(`/* ========== CUSTOM TOKENS ========== */${newline}${newline}`);
    }
    lines.push(exportCustomTokensAsCSS(customTokens, { ...options, selector }));
    tokenCount += customTokens.length;
  }

  // Component overrides
  if (Object.keys(componentOverrides).length > 0) {
    if (includeComments) {
      lines.push(`${newline}/* ========== COMPONENT TOKENS ========== */${newline}${newline}`);
    }

    for (const [componentName, resolved] of Object.entries(componentOverrides)) {
      lines.push(exportComponentTokensAsCSS(componentName, resolved, options));
      tokenCount += Object.keys(resolved).length;
      lines.push(newline);
    }
  }

  const css = lines.join("");

  return {
    css,
    lightMode: css,
    darkMode: undefined, // Could add dark mode variant
    tokenCount,
  };
}

// ============================================
// TAILWIND CONFIG EXPORT
// ============================================

/**
 * Export tokens as Tailwind CSS config extension
 */
export function exportAsTailwindConfig(
  customTokens: CustomToken[]
): string {
  const config: Record<string, Record<string, string>> = {
    colors: {},
    spacing: {},
    borderRadius: {},
    fontSize: {},
    boxShadow: {},
  };

  for (const token of customTokens) {
    const varRef = `var(--custom-${token.id})`;

    switch (token.category) {
      case "color":
        config.colors[token.id] = varRef;
        break;
      case "spacing":
        config.spacing[token.id] = varRef;
        break;
      case "radius":
        config.borderRadius[token.id] = varRef;
        break;
      case "typography":
        config.fontSize[token.id] = varRef;
        break;
      case "shadow":
        config.boxShadow[token.id] = varRef;
        break;
    }
  }

  // Remove empty objects
  for (const key of Object.keys(config)) {
    if (Object.keys(config[key]).length === 0) {
      delete config[key];
    }
  }

  return `// Add to tailwind.config.js theme.extend
module.exports = {
  theme: {
    extend: ${JSON.stringify(config, null, 2)}
  }
}`;
}

// ============================================
// HELPERS
// ============================================

function groupTokensByCategory(
  tokens: CustomToken[]
): Record<string, CustomToken[]> {
  const grouped: Record<string, CustomToken[]> = {};

  for (const token of tokens) {
    if (!grouped[token.category]) {
      grouped[token.category] = [];
    }
    grouped[token.category].push(token);
  }

  return grouped;
}

function formatTokenValue(token: CustomToken): string {
  const value = token.$value;

  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number") {
    return String(value);
  }

  // Complex values (shadow, typography, etc.)
  return JSON.stringify(value);
}
