export interface IconMeta {
  name: string;
  keywords: string[];
  category: string;
}

export const iconCategories = [
  'Numbers & Symbols',
  'A-D',
  'E-H',
  'I-L',
  'M-P',
  'Q-T',
  'U-Z',
] as const;

export type IconCategory = typeof iconCategories[number];

// Sample icons from the design system - this represents the structure
// In a real implementation, this would be auto-generated from the package
export const icons: IconMeta[] = [
  // Numbers & Symbols
  { name: '1CircleFill', keywords: ['one', 'number', 'circle', 'filled'], category: 'Numbers & Symbols' },
  { name: '2CircleFill', keywords: ['two', 'number', 'circle', 'filled'], category: 'Numbers & Symbols' },
  { name: '3CircleFill', keywords: ['three', 'number', 'circle', 'filled'], category: 'Numbers & Symbols' },
  { name: 'AddCircle', keywords: ['plus', 'add', 'circle', 'create'], category: 'Numbers & Symbols' },
  { name: 'AddSquare', keywords: ['plus', 'add', 'square', 'create'], category: 'Numbers & Symbols' },
  { name: 'Minus', keywords: ['subtract', 'remove', 'minus'], category: 'Numbers & Symbols' },
  { name: 'MinusCircle', keywords: ['subtract', 'remove', 'circle'], category: 'Numbers & Symbols' },
  { name: 'Close', keywords: ['x', 'close', 'cancel', 'remove'], category: 'Numbers & Symbols' },
  { name: 'CloseCircle', keywords: ['x', 'close', 'cancel', 'circle'], category: 'Numbers & Symbols' },
  { name: 'Check', keywords: ['checkmark', 'done', 'complete', 'tick'], category: 'Numbers & Symbols' },
  { name: 'CheckCircle', keywords: ['checkmark', 'done', 'circle'], category: 'Numbers & Symbols' },
  { name: 'Percentage', keywords: ['percent', 'discount', 'rate'], category: 'Numbers & Symbols' },
  { name: 'Hash', keywords: ['hashtag', 'number', 'pound'], category: 'Numbers & Symbols' },
  { name: 'At', keywords: ['at', 'email', 'mention'], category: 'Numbers & Symbols' },

  // A-D
  { name: 'Activity', keywords: ['pulse', 'health', 'monitoring'], category: 'A-D' },
  { name: 'Airplay', keywords: ['cast', 'stream', 'screen'], category: 'A-D' },
  { name: 'Alert', keywords: ['warning', 'attention', 'exclamation'], category: 'A-D' },
  { name: 'AlertCircle', keywords: ['warning', 'attention', 'circle'], category: 'A-D' },
  { name: 'AlertTriangle', keywords: ['warning', 'danger', 'triangle'], category: 'A-D' },
  { name: 'Archive', keywords: ['box', 'storage', 'save'], category: 'A-D' },
  { name: 'Arrow', keywords: ['direction', 'navigation'], category: 'A-D' },
  { name: 'ArrowDown', keywords: ['down', 'direction', 'navigation'], category: 'A-D' },
  { name: 'ArrowLeft', keywords: ['left', 'back', 'navigation'], category: 'A-D' },
  { name: 'ArrowRight', keywords: ['right', 'forward', 'navigation'], category: 'A-D' },
  { name: 'ArrowUp', keywords: ['up', 'direction', 'navigation'], category: 'A-D' },
  { name: 'Attachment', keywords: ['paperclip', 'attach', 'file'], category: 'A-D' },
  { name: 'Award', keywords: ['badge', 'achievement', 'medal'], category: 'A-D' },
  { name: 'Bag', keywords: ['shopping', 'cart', 'purchase'], category: 'A-D' },
  { name: 'Bank', keywords: ['finance', 'money', 'building'], category: 'A-D' },
  { name: 'BarChart', keywords: ['graph', 'statistics', 'analytics'], category: 'A-D' },
  { name: 'Battery', keywords: ['power', 'charge', 'energy'], category: 'A-D' },
  { name: 'Bell', keywords: ['notification', 'alert', 'ring'], category: 'A-D' },
  { name: 'Bluetooth', keywords: ['wireless', 'connect', 'device'], category: 'A-D' },
  { name: 'Bold', keywords: ['text', 'format', 'typography'], category: 'A-D' },
  { name: 'Book', keywords: ['read', 'library', 'education'], category: 'A-D' },
  { name: 'Bookmark', keywords: ['save', 'favorite', 'mark'], category: 'A-D' },
  { name: 'Box', keywords: ['container', 'package', 'shipping'], category: 'A-D' },
  { name: 'Briefcase', keywords: ['work', 'business', 'job'], category: 'A-D' },
  { name: 'Building', keywords: ['office', 'company', 'corporate'], category: 'A-D' },
  { name: 'Calendar', keywords: ['date', 'schedule', 'event'], category: 'A-D' },
  { name: 'Camera', keywords: ['photo', 'picture', 'capture'], category: 'A-D' },
  { name: 'Car', keywords: ['vehicle', 'automobile', 'transport'], category: 'A-D' },
  { name: 'Card', keywords: ['credit', 'payment', 'bank'], category: 'A-D' },
  { name: 'Cart', keywords: ['shopping', 'basket', 'purchase'], category: 'A-D' },
  { name: 'Cast', keywords: ['stream', 'broadcast', 'chromecast'], category: 'A-D' },
  { name: 'Chart', keywords: ['graph', 'statistics', 'data'], category: 'A-D' },
  { name: 'Chat', keywords: ['message', 'conversation', 'bubble'], category: 'A-D' },
  { name: 'ChevronDown', keywords: ['arrow', 'expand', 'dropdown'], category: 'A-D' },
  { name: 'ChevronLeft', keywords: ['arrow', 'back', 'previous'], category: 'A-D' },
  { name: 'ChevronRight', keywords: ['arrow', 'forward', 'next'], category: 'A-D' },
  { name: 'ChevronUp', keywords: ['arrow', 'collapse', 'up'], category: 'A-D' },
  { name: 'Circle', keywords: ['shape', 'dot', 'round'], category: 'A-D' },
  { name: 'Clipboard', keywords: ['copy', 'paste', 'notes'], category: 'A-D' },
  { name: 'Clock', keywords: ['time', 'watch', 'schedule'], category: 'A-D' },
  { name: 'Cloud', keywords: ['storage', 'weather', 'sync'], category: 'A-D' },
  { name: 'Code', keywords: ['development', 'programming', 'brackets'], category: 'A-D' },
  { name: 'Coffee', keywords: ['drink', 'cafe', 'beverage'], category: 'A-D' },
  { name: 'Columns', keywords: ['layout', 'grid', 'table'], category: 'A-D' },
  { name: 'Command', keywords: ['keyboard', 'shortcut', 'mac'], category: 'A-D' },
  { name: 'Compass', keywords: ['navigation', 'direction', 'explore'], category: 'A-D' },
  { name: 'Copy', keywords: ['duplicate', 'clipboard', 'paste'], category: 'A-D' },
  { name: 'CreditCard', keywords: ['payment', 'bank', 'finance'], category: 'A-D' },
  { name: 'Crop', keywords: ['image', 'edit', 'resize'], category: 'A-D' },
  { name: 'Database', keywords: ['storage', 'data', 'server'], category: 'A-D' },
  { name: 'Delete', keywords: ['trash', 'remove', 'bin'], category: 'A-D' },
  { name: 'Desktop', keywords: ['computer', 'monitor', 'screen'], category: 'A-D' },
  { name: 'Disc', keywords: ['cd', 'music', 'media'], category: 'A-D' },
  { name: 'Document', keywords: ['file', 'paper', 'page'], category: 'A-D' },
  { name: 'Dollar', keywords: ['money', 'currency', 'finance'], category: 'A-D' },
  { name: 'Download', keywords: ['save', 'arrow', 'get'], category: 'A-D' },
  { name: 'Droplet', keywords: ['water', 'liquid', 'rain'], category: 'A-D' },

  // E-H
  { name: 'Edit', keywords: ['pencil', 'write', 'modify'], category: 'E-H' },
  { name: 'Email', keywords: ['mail', 'envelope', 'message'], category: 'E-H' },
  { name: 'Emoji', keywords: ['smiley', 'face', 'emotion'], category: 'E-H' },
  { name: 'External', keywords: ['link', 'open', 'new window'], category: 'E-H' },
  { name: 'Eye', keywords: ['view', 'visibility', 'show'], category: 'E-H' },
  { name: 'EyeOff', keywords: ['hide', 'invisible', 'hidden'], category: 'E-H' },
  { name: 'Facebook', keywords: ['social', 'media', 'network'], category: 'E-H' },
  { name: 'FastForward', keywords: ['media', 'skip', 'next'], category: 'E-H' },
  { name: 'Feather', keywords: ['light', 'write', 'pen'], category: 'E-H' },
  { name: 'File', keywords: ['document', 'paper', 'page'], category: 'E-H' },
  { name: 'FileText', keywords: ['document', 'text', 'paper'], category: 'E-H' },
  { name: 'Film', keywords: ['movie', 'video', 'cinema'], category: 'E-H' },
  { name: 'Filter', keywords: ['sort', 'funnel', 'refine'], category: 'E-H' },
  { name: 'Flag', keywords: ['mark', 'report', 'country'], category: 'E-H' },
  { name: 'Flame', keywords: ['fire', 'hot', 'trending'], category: 'E-H' },
  { name: 'Folder', keywords: ['directory', 'files', 'organize'], category: 'E-H' },
  { name: 'Gift', keywords: ['present', 'reward', 'bonus'], category: 'E-H' },
  { name: 'GitHub', keywords: ['code', 'repository', 'developer'], category: 'E-H' },
  { name: 'Globe', keywords: ['world', 'earth', 'international'], category: 'E-H' },
  { name: 'Grid', keywords: ['layout', 'tiles', 'gallery'], category: 'E-H' },
  { name: 'Hamburger', keywords: ['menu', 'navigation', 'bars'], category: 'E-H' },
  { name: 'Hash', keywords: ['hashtag', 'number', 'pound'], category: 'E-H' },
  { name: 'Headphones', keywords: ['audio', 'music', 'sound'], category: 'E-H' },
  { name: 'Heart', keywords: ['love', 'like', 'favorite'], category: 'E-H' },
  { name: 'HeartFill', keywords: ['love', 'like', 'favorite'], category: 'E-H' },
  { name: 'Help', keywords: ['question', 'support', 'info'], category: 'E-H' },
  { name: 'History', keywords: ['clock', 'past', 'recent'], category: 'E-H' },
  { name: 'Home', keywords: ['house', 'main', 'dashboard'], category: 'E-H' },

  // I-L
  { name: 'Image', keywords: ['photo', 'picture', 'gallery'], category: 'I-L' },
  { name: 'Inbox', keywords: ['mail', 'messages', 'receive'], category: 'I-L' },
  { name: 'Info', keywords: ['information', 'help', 'details'], category: 'I-L' },
  { name: 'InfoCircle', keywords: ['information', 'help', 'circle'], category: 'I-L' },
  { name: 'Instagram', keywords: ['social', 'photo', 'media'], category: 'I-L' },
  { name: 'Italic', keywords: ['text', 'format', 'typography'], category: 'I-L' },
  { name: 'Key', keywords: ['password', 'security', 'lock'], category: 'I-L' },
  { name: 'Keyboard', keywords: ['type', 'input', 'keys'], category: 'I-L' },
  { name: 'Laptop', keywords: ['computer', 'device', 'notebook'], category: 'I-L' },
  { name: 'Layers', keywords: ['stack', 'depth', 'organize'], category: 'I-L' },
  { name: 'Layout', keywords: ['grid', 'template', 'design'], category: 'I-L' },
  { name: 'Link', keywords: ['chain', 'url', 'connect'], category: 'I-L' },
  { name: 'LinkedIn', keywords: ['social', 'professional', 'network'], category: 'I-L' },
  { name: 'List', keywords: ['items', 'bullet', 'menu'], category: 'I-L' },
  { name: 'Loader', keywords: ['loading', 'spinner', 'wait'], category: 'I-L' },
  { name: 'Location', keywords: ['pin', 'map', 'place'], category: 'I-L' },
  { name: 'Lock', keywords: ['security', 'password', 'private'], category: 'I-L' },
  { name: 'LogIn', keywords: ['sign in', 'enter', 'access'], category: 'I-L' },
  { name: 'LogOut', keywords: ['sign out', 'exit', 'leave'], category: 'I-L' },

  // M-P
  { name: 'Mail', keywords: ['email', 'envelope', 'message'], category: 'M-P' },
  { name: 'Map', keywords: ['location', 'navigation', 'place'], category: 'M-P' },
  { name: 'MapPin', keywords: ['location', 'marker', 'place'], category: 'M-P' },
  { name: 'Maximize', keywords: ['expand', 'fullscreen', 'resize'], category: 'M-P' },
  { name: 'Menu', keywords: ['hamburger', 'navigation', 'bars'], category: 'M-P' },
  { name: 'Message', keywords: ['chat', 'comment', 'bubble'], category: 'M-P' },
  { name: 'Mic', keywords: ['microphone', 'audio', 'record'], category: 'M-P' },
  { name: 'MicOff', keywords: ['microphone', 'mute', 'silent'], category: 'M-P' },
  { name: 'Minimize', keywords: ['collapse', 'shrink', 'resize'], category: 'M-P' },
  { name: 'Money', keywords: ['currency', 'finance', 'cash'], category: 'M-P' },
  { name: 'Monitor', keywords: ['screen', 'display', 'desktop'], category: 'M-P' },
  { name: 'Moon', keywords: ['night', 'dark', 'theme'], category: 'M-P' },
  { name: 'MoreHorizontal', keywords: ['dots', 'menu', 'options'], category: 'M-P' },
  { name: 'MoreVertical', keywords: ['dots', 'menu', 'options'], category: 'M-P' },
  { name: 'Move', keywords: ['drag', 'reorder', 'arrange'], category: 'M-P' },
  { name: 'Music', keywords: ['audio', 'sound', 'song'], category: 'M-P' },
  { name: 'Navigation', keywords: ['arrow', 'direction', 'pointer'], category: 'M-P' },
  { name: 'Notification', keywords: ['bell', 'alert', 'notify'], category: 'M-P' },
  { name: 'Package', keywords: ['box', 'delivery', 'shipping'], category: 'M-P' },
  { name: 'Paperclip', keywords: ['attachment', 'attach', 'file'], category: 'M-P' },
  { name: 'Pause', keywords: ['media', 'stop', 'hold'], category: 'M-P' },
  { name: 'Pen', keywords: ['write', 'edit', 'draw'], category: 'M-P' },
  { name: 'Phone', keywords: ['call', 'mobile', 'contact'], category: 'M-P' },
  { name: 'PieChart', keywords: ['graph', 'statistics', 'data'], category: 'M-P' },
  { name: 'Pin', keywords: ['location', 'mark', 'save'], category: 'M-P' },
  { name: 'Play', keywords: ['media', 'start', 'video'], category: 'M-P' },
  { name: 'Plus', keywords: ['add', 'create', 'new'], category: 'M-P' },
  { name: 'Pocket', keywords: ['save', 'later', 'bookmark'], category: 'M-P' },
  { name: 'Power', keywords: ['on', 'off', 'switch'], category: 'M-P' },
  { name: 'Printer', keywords: ['print', 'document', 'output'], category: 'M-P' },

  // Q-T
  { name: 'QRCode', keywords: ['scan', 'code', 'barcode'], category: 'Q-T' },
  { name: 'Question', keywords: ['help', 'support', 'info'], category: 'Q-T' },
  { name: 'Radio', keywords: ['broadcast', 'music', 'audio'], category: 'Q-T' },
  { name: 'Refresh', keywords: ['reload', 'sync', 'update'], category: 'Q-T' },
  { name: 'Repeat', keywords: ['loop', 'replay', 'cycle'], category: 'Q-T' },
  { name: 'Reply', keywords: ['respond', 'message', 'answer'], category: 'Q-T' },
  { name: 'Rewind', keywords: ['media', 'back', 'previous'], category: 'Q-T' },
  { name: 'Rotate', keywords: ['turn', 'spin', 'orientation'], category: 'Q-T' },
  { name: 'RSS', keywords: ['feed', 'subscribe', 'news'], category: 'Q-T' },
  { name: 'Save', keywords: ['disk', 'store', 'keep'], category: 'Q-T' },
  { name: 'Scissors', keywords: ['cut', 'trim', 'edit'], category: 'Q-T' },
  { name: 'Search', keywords: ['find', 'magnify', 'lookup'], category: 'Q-T' },
  { name: 'Send', keywords: ['message', 'share', 'submit'], category: 'Q-T' },
  { name: 'Server', keywords: ['database', 'hosting', 'backend'], category: 'Q-T' },
  { name: 'Settings', keywords: ['gear', 'config', 'preferences'], category: 'Q-T' },
  { name: 'Share', keywords: ['send', 'social', 'export'], category: 'Q-T' },
  { name: 'Shield', keywords: ['security', 'protect', 'safe'], category: 'Q-T' },
  { name: 'ShoppingBag', keywords: ['cart', 'purchase', 'buy'], category: 'Q-T' },
  { name: 'ShoppingCart', keywords: ['cart', 'purchase', 'buy'], category: 'Q-T' },
  { name: 'Shuffle', keywords: ['random', 'mix', 'reorder'], category: 'Q-T' },
  { name: 'Sidebar', keywords: ['panel', 'menu', 'navigation'], category: 'Q-T' },
  { name: 'Signal', keywords: ['wifi', 'connection', 'network'], category: 'Q-T' },
  { name: 'Sliders', keywords: ['settings', 'adjust', 'control'], category: 'Q-T' },
  { name: 'Smartphone', keywords: ['mobile', 'phone', 'device'], category: 'Q-T' },
  { name: 'Sort', keywords: ['order', 'arrange', 'filter'], category: 'Q-T' },
  { name: 'Speaker', keywords: ['audio', 'sound', 'volume'], category: 'Q-T' },
  { name: 'Square', keywords: ['shape', 'box', 'rectangle'], category: 'Q-T' },
  { name: 'Star', keywords: ['favorite', 'rating', 'bookmark'], category: 'Q-T' },
  { name: 'StarFill', keywords: ['favorite', 'rating', 'filled'], category: 'Q-T' },
  { name: 'Stop', keywords: ['media', 'halt', 'end'], category: 'Q-T' },
  { name: 'Sun', keywords: ['light', 'day', 'theme'], category: 'Q-T' },
  { name: 'Table', keywords: ['data', 'grid', 'spreadsheet'], category: 'Q-T' },
  { name: 'Tablet', keywords: ['device', 'ipad', 'mobile'], category: 'Q-T' },
  { name: 'Tag', keywords: ['label', 'category', 'badge'], category: 'Q-T' },
  { name: 'Target', keywords: ['goal', 'focus', 'aim'], category: 'Q-T' },
  { name: 'Terminal', keywords: ['console', 'command', 'shell'], category: 'Q-T' },
  { name: 'ThumbsDown', keywords: ['dislike', 'negative', 'bad'], category: 'Q-T' },
  { name: 'ThumbsUp', keywords: ['like', 'positive', 'good'], category: 'Q-T' },
  { name: 'Toggle', keywords: ['switch', 'on', 'off'], category: 'Q-T' },
  { name: 'Tool', keywords: ['wrench', 'settings', 'repair'], category: 'Q-T' },
  { name: 'Trash', keywords: ['delete', 'remove', 'bin'], category: 'Q-T' },
  { name: 'TrendingDown', keywords: ['decrease', 'arrow', 'chart'], category: 'Q-T' },
  { name: 'TrendingUp', keywords: ['increase', 'arrow', 'chart'], category: 'Q-T' },
  { name: 'Triangle', keywords: ['shape', 'warning', 'play'], category: 'Q-T' },
  { name: 'Twitter', keywords: ['social', 'media', 'x'], category: 'Q-T' },

  // U-Z
  { name: 'Umbrella', keywords: ['weather', 'rain', 'protect'], category: 'U-Z' },
  { name: 'Underline', keywords: ['text', 'format', 'typography'], category: 'U-Z' },
  { name: 'Undo', keywords: ['back', 'revert', 'history'], category: 'U-Z' },
  { name: 'Unlock', keywords: ['open', 'access', 'security'], category: 'U-Z' },
  { name: 'Upload', keywords: ['send', 'arrow', 'share'], category: 'U-Z' },
  { name: 'User', keywords: ['person', 'account', 'profile'], category: 'U-Z' },
  { name: 'UserCircle', keywords: ['person', 'account', 'avatar'], category: 'U-Z' },
  { name: 'UserPlus', keywords: ['add', 'person', 'new'], category: 'U-Z' },
  { name: 'Users', keywords: ['people', 'group', 'team'], category: 'U-Z' },
  { name: 'Video', keywords: ['camera', 'record', 'film'], category: 'U-Z' },
  { name: 'VideoOff', keywords: ['camera', 'mute', 'disabled'], category: 'U-Z' },
  { name: 'Volume', keywords: ['sound', 'audio', 'speaker'], category: 'U-Z' },
  { name: 'VolumeOff', keywords: ['mute', 'silent', 'audio'], category: 'U-Z' },
  { name: 'Wallet', keywords: ['money', 'finance', 'payment'], category: 'U-Z' },
  { name: 'Watch', keywords: ['time', 'clock', 'wearable'], category: 'U-Z' },
  { name: 'Wifi', keywords: ['internet', 'wireless', 'signal'], category: 'U-Z' },
  { name: 'WifiOff', keywords: ['internet', 'offline', 'signal'], category: 'U-Z' },
  { name: 'Wind', keywords: ['weather', 'air', 'breeze'], category: 'U-Z' },
  { name: 'Window', keywords: ['app', 'browser', 'frame'], category: 'U-Z' },
  { name: 'X', keywords: ['close', 'cancel', 'remove'], category: 'U-Z' },
  { name: 'XCircle', keywords: ['close', 'cancel', 'circle'], category: 'U-Z' },
  { name: 'Youtube', keywords: ['video', 'social', 'media'], category: 'U-Z' },
  { name: 'ZoomIn', keywords: ['magnify', 'enlarge', 'scale'], category: 'U-Z' },
  { name: 'ZoomOut', keywords: ['shrink', 'reduce', 'scale'], category: 'U-Z' },
  { name: 'Zap', keywords: ['lightning', 'fast', 'power'], category: 'U-Z' },
];

export const getIconsByCategory = (category: IconCategory): IconMeta[] => {
  return icons.filter(icon => icon.category === category);
};

export const searchIcons = (query: string): IconMeta[] => {
  const lowerQuery = query.toLowerCase();
  return icons.filter(icon => 
    icon.name.toLowerCase().includes(lowerQuery) ||
    icon.keywords.some(kw => kw.includes(lowerQuery))
  );
};

export const getIconImportPath = (iconName: string): string => {
  return `import { ${iconName} } from '@marcelinodzn/ds-react/icons';`;
};

export const getIconUsageCode = (iconName: string): string => {
  return `<${iconName} size={24} />`;
};
